name: Build Docker Image

on:
    pull_request:
        branches: ["staging"]

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile
