name: Add contributors
on:
    push:
        branches: ["development"]

jobs:
    add-contributors:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: BobAnkh/add-contributors@master
              with:
                  CONTRIBUTOR: "## Contributors"
                  COLUMN_PER_ROW: "6"
                  ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  IMG_WIDTH: "100"
                  FONT_SIZE: "14"
                  PATH: "/README.md"
                  BRANCH: "development"
                  PULL_REQUEST: "development"
                  COMMIT_MESSAGE: "Docs (README): update contributors"
                  AVATAR_SHAPE: "square"
